name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          (python -m pip install -r requirements.txt || true)
          python -m pip install -r requirements-dev.txt
      - name: Lint
        run: flake8 . --ignore=E731,E402,E702,F401,F403
      - name: Type check
        run: mypy src modules || true
      - name: Tests
        run: pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=xml | tee pytest-report.log
      - name: Smoke test UI
        run: python -c "import modules.ui.app as m; print(bool(getattr(m, 'build_app', None)))"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-tests
          path: |
            coverage.xml
            pytest-report.log
